export interface getCompanyProps {
    id: number,
    comp_cd: string,
    comp_nm: string,
    comp_type: string,
    domain: string,
    mobile_no: string,
    email_id: string,
    address_1: string,
    city: string,
    state: string,
    country: string,
    two_fa: boolean,
    pin_cd: string,
    is_active: boolean,
    entry_by: number | null,
    entry_dt: Date | null,
    update_by: number | null,
    update_dt: Date | null,
}

export interface getCompanyDtlProps {
    id: number,
    comp_cd: string,
    comp_nm: string,
    comp_type: string,
    domain: string,
    mobile_no: string,
    email_id: string,
    address_1: string,
    address_2: string,
    city: string,
    state: string,
    country: string,
    two_fa: boolean,
    pin_cd: string,
    is_active: boolean,
    logo: string | null,
    logo_height: number | null,
    logo_width: number | null,
    fav_icon: string | null,
    is_sms: boolean,
    sms_method: "POST" | "GET" | null,
    sms_url: string | null,
    is_email: boolean,
    smtp_host: string | null,
    smtp_port: string | null,
    smtp_tls: string,
    smtp_usernm: string | null,
    smtp_password: string | null,
    smtp_from_email: string | null,
    entry_by: number | null,
    entry_dt: Date | null,
    update_by: number | null,
    update_dt: Date | null,
}